### ISSUE TITLE
relationship designators not working in QA

### ISSUE THREAD

**Issue by CECSpecialistI** [LD4P/sinopia_editor#1209]
**Describe the bug**
What went wrong? What did you expect to happen?
Trying to add a relator term to a contribution, I got an error message "Unable to find http://id.loc.gov/vocabulary/relators in the lookup configuration"

- What is the impact on your work? can't add relationship designators through lookup but can enter literals. Still a problem, because we should be able to add them through QA?
- What environment are you in? stage
- What OS and browser are you using? windows/chrome
- If you're cataloging, what Resource Template were you using (name or ID)
harvard:rt:test:userfeedback
**Please include a screenshot**
![image](https://user-images.githubusercontent.com/43214565/63045225-c6190600-be84-11e9-87f1-b9892e4e82a9.png)

**Comment by michelleif** [comment]
Hi, I've fixed the referenced RT lc:RT:bf2:Agent:Role which was using lookup value http://id.loc.gov/vocabulary/relators where Sinopia requires https. @CECSpecialistI can you try it again now? (thanks @jermnelson for troubleshooting)

**Comment by ctenor** [comment]
Hi, I am still getting this error message as of today (8/15; 1:26 pm, est)

**Comment by michelleif** [comment]
confirmed that this is working now
