### ISSUE TITLE
Nested defaults for literals don't allow for editing

### ISSUE THREAD

**Issue by alexiskeely** [LD4P/sinopia_editor#1306]
When a PT with a default literal is in a nested RT, the default literal disappears when edit is clicked.

![image](https://user-images.githubusercontent.com/37376659/64724730-ec33c500-d487-11e9-8c73-3c32e26aa150.png)

In the image above, "n" disappears from the PT when attempting to edit. 
Browser: chrome, opera
RT: WAU:RT:RDA:Work:monograph

**Comment by michelleif** [comment]
check again after #1273 is fixed

**Comment by michelleif** [comment]
fixed by #1273

**Comment by alexiskeely** [comment]
Problem still persists in WAU:RT:RDA:Manifestation:map on stage and dev for the property shown above (AdminMetada > Status > Code).

**Comment by michelleif** [comment]
ack! thanks alexis. I think I mistakenly tested this in WAU:RT:BF2:BFLC:AdminMetadata rather than WAU:RT:RDA:Manifestation:map or WAU:RT:RDA:Work:monograph

i'll put this high on the priority list to get fixed

**Comment by michelleif** [comment]
NOTE: this example is with inputLookupLiteral (and the earlier fix on nested lookups dealt with inputLookupQA so would not have fixed this.)
